project:
  type: website

website:
  title: "Francesca's Explorations with LLMs"
  navbar:
    right:
      - about.qmd
format:
  html:
    theme: journal
    css: styles.css

execute:
  freeze: auto




